name = "MarkdownLiteral"
uuid = "736d6165-7244-6769-4267-6b50796e6954"
authors = ["Fons van der Plas <fons@plutojl.org>"]
version = "0.1.3"

[deps]
CommonMark = "a80b9123-70ca-4bc0-993e-6e3bcb318db6"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"

[compat]
julia = "1.3"
CommonMark = "0.8, 0.9, 0.10"
HypertextLiteral = "0.9, 1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
